name: Build_Nexus
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup_Theos
        uses: pypush/actions-theos-v2@v1

      - name: Build_Tweak
        run: |
          export THEOS=~/theos
          make package FINALPACKAGE=1
          
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Nexus_Dylib
          path: packages/*.deb
