name: Build_Nexus
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Theos
        uses: pypush/actions-theos-v2@v1

      - name: Build
        run: |
          make package FINALPACKAGE=1
          
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Nexus_Dylib
          path: packages/*.deb
