name: Build Nexus Dylib
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Theos
        uses: pypush/actions-theos-v2@v1

      - name: Build Tweak
        run: |
          # Comando para compilar mesmo que os arquivos estejam na raiz
          make package FINALPACKAGE=1
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: NexusVIP-Dylib
          path: packages/*.deb
